name: Build Linux

on:
  push:
    paths-ignore:
    - 'LICENSE'
    - 'README.md'
    - 'SECURITY.md'
    - '_config.yml'

jobs:
  build:
    name: CI on ${{ matrix.tag }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        tag: # Those are alire's dockerhub alire/gnat:tag machines
	  - community-2019
          - community-2020
          - centos-latest-community-2019
          - centos-latest-community-2020
          #- debian-stable (no GNATColl atm)
          #- ubuntu-lts (no GNATColl atm)

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Pull docker image
        run: docker pull alire/gnat:${{ matrix.tag }}
      - name: Build
        run: >
          docker run -v${PWD}:/spat -w /spat
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} bash .github/scripts/ci-build.sh
      - name: Run tests
        run: >
          docker run -v${PWD}:/spat -w /spat
          -e "BRANCH=${{ github.base_ref }}"
          alire/gnat:${{ matrix.tag }} bash .github/scripts/ci-test.sh
